### ISSUE TITLE
LocalDailyScript not available

### ISSUE THREAD

**Issue by AllinsonG** [SebastianoMeneghin/sml-project-2023-manfredi-meneghin#1]
I want to run the GitHub and replicate the code in a local Ubuntu python machine, but the localdailyscript doesn't available to be provided as of I search now. Could you please enlighten me on how to access this page: https://github.com/SebastianoMeneghin/sml-project-2023-manfredi-meneghin/tree/main/src/local_daily_scripts. Thank you.

**Comment by SebastianoMeneghin** [comment]
Dear Allison!
We have slightly changed the location of the code, you can find it in https://github.com/SebastianoMeneghin/sml-project-2023-manfredi-meneghin/tree/main/src/other/local_daily_scripts.
Can you tell me where you found the not working link, so I can add the new one on the readme?

Thanks!

**Comment by SebastianoMeneghin** [comment]
Update on this issue: @AllinsonG I've found the error and corrected this inconsistency.
Thanks for warning us about this!

Let us know if this code will help you with your projects.
